spring:
    datasource:
        username: root
        password: 123456
        url: jdbc:mysql://192.168.2.79:3306/jdbc
        driver-calss-name: com.mysql.cj.jdbc.Driver

        type: com.alibaba.druid.pool.DruidDataSource

        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙; logback 为SpringBoot的默认日志框架
        filters: stat,wall,logback
        maxPoolPreparedStatementPerConnectionSize: 20
        useGlobalDataSourceStat: true
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    # SQL初始化 建表语句
    #    schema:
    #      - classpath:department.sql